// Mocks generated by Mockito 5.4.6 from annotations
// in uni_finder/test/test_utils/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i24;
import 'package:uni_finder/Domain/data/repository/career_repository.dart'
    as _i21;
import 'package:uni_finder/Domain/data/repository/dream_repository.dart'
    as _i12;
import 'package:uni_finder/Domain/data/repository/major_repository.dart' as _i9;
import 'package:uni_finder/Domain/data/repository/question_repository.dart'
    as _i14;
import 'package:uni_finder/Domain/data/repository/relationship_repository.dart'
    as _i5;
import 'package:uni_finder/Domain/data/repository/university_repository.dart'
    as _i2;
import 'package:uni_finder/Domain/data/repository/user_repository.dart' as _i19;
import 'package:uni_finder/Domain/data/storage/file_storage.dart' as _i23;
import 'package:uni_finder/Domain/data/storage/shared_preferences_storage.dart'
    as _i22;
import 'package:uni_finder/Domain/model/Career/career_major.dart' as _i6;
import 'package:uni_finder/Domain/model/Career/career_model.dart' as _i8;
import 'package:uni_finder/Domain/model/Category/category_model.dart' as _i15;
import 'package:uni_finder/Domain/model/Dream/dreams_model.dart' as _i13;
import 'package:uni_finder/Domain/model/Major/major_model.dart' as _i10;
import 'package:uni_finder/Domain/model/Major/major_relationship.dart' as _i11;
import 'package:uni_finder/Domain/model/Quiz/option_model.dart' as _i17;
import 'package:uni_finder/Domain/model/Quiz/question_model.dart' as _i16;
import 'package:uni_finder/Domain/model/Quiz/submission_model.dart' as _i18;
import 'package:uni_finder/Domain/model/University/university_major.dart'
    as _i7;
import 'package:uni_finder/Domain/model/University/university_model.dart'
    as _i4;
import 'package:uni_finder/Domain/model/User/user_model.dart' as _i20;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UniversityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUniversityRepository extends _i1.Mock
    implements _i2.UniversityRepository {
  MockUniversityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.University>> getUniversitiesData() =>
      (super.noSuchMethod(
            Invocation.method(#getUniversitiesData, []),
            returnValue: _i3.Future<List<_i4.University>>.value(
              <_i4.University>[],
            ),
          )
          as _i3.Future<List<_i4.University>>);

  @override
  _i3.Future<_i4.University?> getUniversityById(String? universityId) =>
      (super.noSuchMethod(
            Invocation.method(#getUniversityById, [universityId]),
            returnValue: _i3.Future<_i4.University?>.value(),
          )
          as _i3.Future<_i4.University?>);
}

/// A class which mocks [RelationshipRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelationshipRepository extends _i1.Mock
    implements _i5.RelationshipRepository {
  MockRelationshipRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.CareerMajor>> getCareerMajorsData() =>
      (super.noSuchMethod(
            Invocation.method(#getCareerMajorsData, []),
            returnValue: _i3.Future<List<_i6.CareerMajor>>.value(
              <_i6.CareerMajor>[],
            ),
          )
          as _i3.Future<List<_i6.CareerMajor>>);

  @override
  _i3.Future<List<_i7.UniversityMajor>> getUniversityMajorsData() =>
      (super.noSuchMethod(
            Invocation.method(#getUniversityMajorsData, []),
            returnValue: _i3.Future<List<_i7.UniversityMajor>>.value(
              <_i7.UniversityMajor>[],
            ),
          )
          as _i3.Future<List<_i7.UniversityMajor>>);

  @override
  _i3.Future<List<_i8.Career>> getCareersByMajor(
    String? majorId,
    List<_i8.Career>? allCareers,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCareersByMajor, [majorId, allCareers]),
            returnValue: _i3.Future<List<_i8.Career>>.value(<_i8.Career>[]),
          )
          as _i3.Future<List<_i8.Career>>);

  @override
  _i3.Future<List<_i7.UniversityMajor>> getUniversitiesForMajor(
    String? majorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUniversitiesForMajor, [majorId]),
            returnValue: _i3.Future<List<_i7.UniversityMajor>>.value(
              <_i7.UniversityMajor>[],
            ),
          )
          as _i3.Future<List<_i7.UniversityMajor>>);
}

/// A class which mocks [MajorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMajorRepository extends _i1.Mock implements _i9.MajorRepository {
  MockMajorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i10.Major>> getMajorsData() =>
      (super.noSuchMethod(
            Invocation.method(#getMajorsData, []),
            returnValue: _i3.Future<List<_i10.Major>>.value(<_i10.Major>[]),
          )
          as _i3.Future<List<_i10.Major>>);

  @override
  _i3.Future<_i10.Major?> getMajorById(String? majorId) =>
      (super.noSuchMethod(
            Invocation.method(#getMajorById, [majorId]),
            returnValue: _i3.Future<_i10.Major?>.value(),
          )
          as _i3.Future<_i10.Major?>);

  @override
  _i3.Future<List<_i10.Major>> getMajorsByIds(List<String>? majorIds) =>
      (super.noSuchMethod(
            Invocation.method(#getMajorsByIds, [majorIds]),
            returnValue: _i3.Future<List<_i10.Major>>.value(<_i10.Major>[]),
          )
          as _i3.Future<List<_i10.Major>>);

  @override
  _i3.Future<List<_i10.Major>> getRelatedMajors(String? majorId) =>
      (super.noSuchMethod(
            Invocation.method(#getRelatedMajors, [majorId]),
            returnValue: _i3.Future<List<_i10.Major>>.value(<_i10.Major>[]),
          )
          as _i3.Future<List<_i10.Major>>);

  @override
  _i3.Future<List<_i11.MajorRelationship>> getMajorRelationshipsData() =>
      (super.noSuchMethod(
            Invocation.method(#getMajorRelationshipsData, []),
            returnValue: _i3.Future<List<_i11.MajorRelationship>>.value(
              <_i11.MajorRelationship>[],
            ),
          )
          as _i3.Future<List<_i11.MajorRelationship>>);

  @override
  _i3.Future<Map<String, List<String>>> getMajorRelationships() =>
      (super.noSuchMethod(
            Invocation.method(#getMajorRelationships, []),
            returnValue: _i3.Future<Map<String, List<String>>>.value(
              <String, List<String>>{},
            ),
          )
          as _i3.Future<Map<String, List<String>>>);
}

/// A class which mocks [DreamRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDreamRepository extends _i1.Mock implements _i12.DreamRepository {
  MockDreamRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i13.Dream>> getDreams() =>
      (super.noSuchMethod(
            Invocation.method(#getDreams, []),
            returnValue: _i3.Future<List<_i13.Dream>>.value(<_i13.Dream>[]),
          )
          as _i3.Future<List<_i13.Dream>>);

  @override
  _i3.Future<void> saveDream(_i13.Dream? dream) =>
      (super.noSuchMethod(
            Invocation.method(#saveDream, [dream]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDream(String? dreamId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDream, [dreamId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [QuestionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestionRepository extends _i1.Mock
    implements _i14.QuestionRepository {
  MockQuestionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i15.Category>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i3.Future<List<_i15.Category>>.value(
              <_i15.Category>[],
            ),
          )
          as _i3.Future<List<_i15.Category>>);

  @override
  _i3.Future<List<_i16.Question>> getQuestionData() =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionData, []),
            returnValue: _i3.Future<List<_i16.Question>>.value(
              <_i16.Question>[],
            ),
          )
          as _i3.Future<List<_i16.Question>>);

  @override
  _i3.Future<List<_i17.Option>> getOptionData() =>
      (super.noSuchMethod(
            Invocation.method(#getOptionData, []),
            returnValue: _i3.Future<List<_i17.Option>>.value(<_i17.Option>[]),
          )
          as _i3.Future<List<_i17.Option>>);

  @override
  _i3.Future<Map<String, List<_i17.Option>>> getOptionsByQuestion() =>
      (super.noSuchMethod(
            Invocation.method(#getOptionsByQuestion, []),
            returnValue: _i3.Future<Map<String, List<_i17.Option>>>.value(
              <String, List<_i17.Option>>{},
            ),
          )
          as _i3.Future<Map<String, List<_i17.Option>>>);

  @override
  _i3.Future<List<_i18.Submission>> getSubmissionData() =>
      (super.noSuchMethod(
            Invocation.method(#getSubmissionData, []),
            returnValue: _i3.Future<List<_i18.Submission>>.value(
              <_i18.Submission>[],
            ),
          )
          as _i3.Future<List<_i18.Submission>>);

  @override
  _i3.Future<void> saveSubmission(_i18.Submission? submit) =>
      (super.noSuchMethod(
            Invocation.method(#saveSubmission, [submit]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i19.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i20.User?> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i3.Future<_i20.User?>.value(),
          )
          as _i3.Future<_i20.User?>);

  @override
  _i3.Future<void> saveUser(_i20.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [CareerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCareerRepository extends _i1.Mock implements _i21.CareerRepository {
  MockCareerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i8.Career>> getCareerData() =>
      (super.noSuchMethod(
            Invocation.method(#getCareerData, []),
            returnValue: _i3.Future<List<_i8.Career>>.value(<_i8.Career>[]),
          )
          as _i3.Future<List<_i8.Career>>);

  @override
  _i3.Future<_i8.Career?> getCareerById(String? careerId) =>
      (super.noSuchMethod(
            Invocation.method(#getCareerById, [careerId]),
            returnValue: _i3.Future<_i8.Career?>.value(),
          )
          as _i3.Future<_i8.Career?>);
}

/// A class which mocks [SharedPreferencesStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesStorage extends _i1.Mock
    implements _i22.SharedPreferencesStorage {
  MockSharedPreferencesStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveUser(_i20.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i20.User?> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i3.Future<_i20.User?>.value(),
          )
          as _i3.Future<_i20.User?>);

  @override
  _i3.Future<void> saveDreams(List<_i13.Dream>? dreams) =>
      (super.noSuchMethod(
            Invocation.method(#saveDreams, [dreams]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i13.Dream>> getUserDreams() =>
      (super.noSuchMethod(
            Invocation.method(#getUserDreams, []),
            returnValue: _i3.Future<List<_i13.Dream>>.value(<_i13.Dream>[]),
          )
          as _i3.Future<List<_i13.Dream>>);

  @override
  _i3.Future<void> deleteDream(String? dreamId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDream, [dreamId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [FileStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileStorage extends _i1.Mock implements _i23.FileStorage {
  MockFileStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get directoryPath =>
      (super.noSuchMethod(
            Invocation.getter(#directoryPath),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#directoryPath),
            ),
          )
          as String);

  @override
  _i3.Future<List<dynamic>> readJsonData(String? filename) =>
      (super.noSuchMethod(
            Invocation.method(#readJsonData, [filename]),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<void> writeJson(String? filename, List<dynamic>? jsonList) =>
      (super.noSuchMethod(
            Invocation.method(#writeJson, [filename, jsonList]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
